# Generated by Django 3.2.5 on 2022-01-04 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 17, 54, 3, 447161, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
